#### Importar Dados da Lotofácil

In [124]:
import pandas as pd
import numpy as np
import os

directory = os.getcwd()

os.chdir(directory)

In [125]:
path_file = 'Lotofácil.xlsx'

df = pd.read_excel(path_file, sheet_name='LOTOFÁCIL', header=0)

In [126]:
df = df[['Concurso', 'Data Sorteio', 'Bola1', 'Bola2', 'Bola3', 'Bola4', 'Bola5', 'Bola6', 'Bola7', 'Bola8', 'Bola9', 'Bola10', 'Bola11', 'Bola12', 'Bola13', 'Bola14', 'Bola15', 'Ganhadores 15 acertos', 'Rateio 15 acertos']]

df['Premio 15 acertos'] = df['Rateio 15 acertos'].str.replace('R$', '').str.replace('.', '').str.replace(',', '.').astype(float)

df['Total'] = df['Ganhadores 15 acertos'] * df['Premio 15 acertos']

In [127]:
df.sort_values('Concurso', ascending=False, inplace=True)

In [6]:
# Filtrar por últimos 100 concursos.
qtde_concursos = 100
df_final_0 = df.head(qtde_concursos).reset_index(drop=True)

#### Analisar premiação concurso final 0

In [118]:
df_final_0 = df[df['Concurso'] % 10 == 0].sort_values('Concurso', ascending=False)

#### Números mais sorteados.

In [7]:
# Df count values.
df_count = pd.DataFrame({'numero': list(range(1, 26)), 'vezes sorteado': [0] * 25})

In [8]:
# Somar a qtde de vezes que cada número apareceu em todas as colunas 'BolaX' e adicionar no df_count.

ball_cols = [f'Bola{i}' for i in range(1, 16)]
all_balls = df[ball_cols].values.flatten()
counts = pd.Series(all_balls).value_counts()
df_count['vezes sorteado'] = df_count['numero'].map(counts).fillna(0).astype(int)

# Ordenar pelo maior para menor.
df_count.sort_values('vezes sorteado', ascending=False, inplace=True, ignore_index=True)

In [35]:
array_jogos = df[['Bola1', 'Bola2', 'Bola3', 'Bola4', 'Bola5', 'Bola6', 'Bola7', 'Bola8', 'Bola9', 'Bola10', 'Bola11', 'Bola12', 'Bola13', 'Bola14', 'Bola15']].values


In [36]:
display(df_count)

,numero,vezes sorteado
0,20,2237
1,10,2224
2,25,2223
3,11,2200
4,13,2181
5,24,2176
6,14,2175
7,1,2168
8,4,2163
9,3,2161


#### Teste de jogos.

In [97]:
#### Teste de jogos.
from itertools import combinations

numeros_fixos = [1, 3, 4, 10, 11, 13, 14, 20, 24, 25] # 5
numeros_fixos = [1, 4, 5, 7, 8, 10, 12, 20, 22, 25] 
numeros_fixos = [1, 4, 10, 11, 13, 14, 20, 24, 25]  # 811 jogos.
numeros_fixos = [1, 9, 10, 11, 12, 13, 14, 20, 24, 25]
numeros_fixos = [1, 2, 9, 10, 12, 13, 20, 24, 25]  #! MAIS TOP.
numeros_fixos = [1, 10, 20, 25]

c = 0
for jogo in array_jogos:
    if all(num in jogo for num in numeros_fixos):
        #print(jogo)
        c += 1
print(f'Total de jogos encontrados: {c}')

Total de jogos encontrados: 442


In [98]:
##### NÚMEROS NÃO JOGAR #####
numeros_nao_jogar = [3, 5]

In [99]:
#### Mostrar os jogos que contém os números fixos.
for jogo in array_jogos:
    if all(num in jogo for num in numeros_fixos):
        print(jogo)

[ 1  2  3  4  8 10 11 13 15 17 19 20 21 23 25]
[ 1  2  4  5  6  8  9 10 12 16 18 20 23 24 25]
[ 1  2  7  8 10 11 12 14 15 16 17 20 22 23 25]
[ 1  2  4  8  9 10 11 12 14 15 18 19 20 24 25]
[ 1  4 10 11 13 16 17 18 19 20 21 22 23 24 25]
[ 1  3  4  9 10 11 12 13 15 17 19 20 21 23 25]
[ 1  2  4  5  6  7  8 10 15 16 17 18 20 21 25]
[ 1  2  6  8  9 10 11 13 14 15 16 19 20 24 25]
[ 1  4  5  6  8 10 11 12 15 17 20 21 22 23 25]
[ 1  2  3  4  7  9 10 12 15 19 20 21 22 24 25]
[ 1  3  5  6  7  9 10 16 18 19 20 22 23 24 25]
[ 1  2  4  5  9 10 13 14 15 17 19 20 22 24 25]
[ 1  4  6  8  9 10 12 13 14 15 18 19 20 21 25]
[ 1  2  9 10 13 14 15 16 17 18 19 20 22 24 25]
[ 1  2  4  6  9 10 11 12 16 17 18 20 22 23 25]
[ 1  3  5  7  9 10 11 12 14 16 17 20 21 23 25]
[ 1  4  5  6  8 10 11 12 13 15 16 19 20 24 25]
[ 1  2  3  4  6  7  9 10 12 13 15 17 19 20 25]
[ 1  2  5  6 10 13 14 15 16 18 20 22 23 24 25]
[ 1  2  4  7  9 10 11 13 14 15 18 19 20 24 25]
[ 1  4  6  7 10 11 12 14 15 16 17 20 21 23 25]
[ 1  4  5  6 

In [100]:
#### Quais são os números que mais aparecem junto com os números fixos nos jogos encontrados.
from collections import Counter

numeros_complementares = []
for jogo in array_jogos:
    if all(num in jogo for num in numeros_fixos):
        for num in jogo:
            if num not in numeros_fixos:
                numeros_complementares.append(num)
contador = Counter(numeros_complementares)
for numero, frequencia in contador.most_common():  
    print(f'Número: {numero}, Frequência: {frequencia}')

Número: 11, Frequência: 243
Número: 12, Frequência: 242
Número: 14, Frequência: 242
Número: 13, Frequência: 241
Número: 24, Frequência: 240
Número: 9, Frequência: 239
Número: 18, Frequência: 236
Número: 23, Frequência: 235
Número: 3, Frequência: 233
Número: 17, Frequência: 232
Número: 19, Frequência: 232
Número: 2, Frequência: 231
Número: 8, Frequência: 230
Número: 21, Frequência: 229
Número: 6, Frequência: 228
Número: 15, Frequência: 224
Número: 5, Frequência: 223
Número: 4, Frequência: 222
Número: 16, Frequência: 220
Número: 7, Frequência: 220
Número: 22, Frequência: 220


In [101]:
#### Jogos que não tenham os números fixos.
total_jogos = 0
for jogo in array_jogos:
    if all(num not in jogo for num in numeros_fixos):
        print(jogo)
        total_jogos += 1
print(f'Total de jogos sem os números fixos: {total_jogos}')


[ 2  3  4  5  7  9 12 13 14 15 16 17 18 22 24]
[ 2  3  4  6  7  9 11 12 14 16 17 18 19 21 24]
[ 3  4  6  7 11 12 13 14 16 17 19 21 22 23 24]
[ 3  5  6  8  9 11 12 13 14 16 17 21 22 23 24]
[ 2  3  4  5  7  9 12 14 15 16 19 21 22 23 24]
[ 2  4  5  7  8 12 13 14 16 17 18 19 21 22 23]
[ 3  4  6  7  8 11 12 13 14 16 19 21 22 23 24]
[ 2  5  7  8  9 11 12 13 14 16 17 19 21 23 24]
[ 2  3  5  6  7  8  9 12 14 15 16 18 19 21 24]
[ 2  3  4  5  6  7  8  9 11 15 17 18 19 21 23]
[ 2  4  5  7  9 12 13 14 15 18 19 21 22 23 24]
[ 2  3  5  6  7  8  9 12 13 16 18 19 21 22 24]
[ 2  4  6  7  8  9 11 12 13 14 15 16 17 21 24]
[ 2  5  6  7  9 11 12 14 15 17 19 21 22 23 24]
[ 2  3  4  5  6  7  8  9 11 13 15 18 22 23 24]
[ 3  4  5  7  8 11 12 13 14 15 17 18 19 22 24]
[ 2  4  5  6  7  8 11 12 13 15 16 18 21 22 24]
[ 3  4  5  6  8  9 11 13 14 15 16 17 18 23 24]
[ 2  3  4  5  7  8 12 13 16 17 18 19 21 22 23]
[ 2  5  6  8  9 11 13 14 15 16 18 19 21 22 23]
[ 2  3  4  6  8 12 13 14 15 16 19 21 22 23 24]
[ 2  3  5  7 

#### Analizes de jogos feitos

In [132]:
#### JOGOS ####
jogos = {
    'Lore': [1, 2, 4, 6, 7, 10, 11, 12, 14, 15, 18, 20, 22, 24, 25],
    'Cida': [1, 2, 4, 6, 8, 9, 10, 12, 13, 17, 19, 20, 21, 24, 25],
    'Joao': [1, 2, 4, 6, 7, 9, 10, 12, 13, 16, 18, 20, 23, 24, 25]
}

# Qtde de acertos por jogo nos últimos 100 concursos.
acertos_por_jogo = {
    'Lore': [],
    'Cida': [],
    'Joao': []
}


for jogo in array_jogos[0:50]:
    for nome, numeros in jogos.items():
        acertos = len(set(jogo) & set(numeros))
        if acertos >= 11:
            acertos_por_jogo[nome].append(acertos)

print('Qtde de jogos:', len(array_jogos[0:50]))
for nome, acertos in acertos_por_jogo.items():
    print(f'{nome}: {len(acertos)} acertos | Detalhes: {acertos}')

# Total de acertos somando todos os nomes.
total_acertos = sum([len(acertos) for nome, acertos in acertos_por_jogo.items()])
print(f'\nTotal de acertos somando todos os nomes: {total_acertos}')

Qtde de jogos: 50
Lore: 6 acertos | Detalhes: [11, 11, 11, 12, 11, 11]
Cida: 9 acertos | Detalhes: [11, 11, 11, 11, 11, 11, 11, 11, 11]
Joao: 4 acertos | Detalhes: [13, 11, 11, 11]

Total de acertos somando todos os nomes: 19
